<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PackageId>FlyingFury.Yeti.Persistence</PackageId>
	<Version>0.0.1</Version>
	<Authors>Flying Fury</Authors>
	<Company>Flying Fury</Company>
	<Description>Database access layer for the Yeti project</Description>
	<PackageTags>Persistance</PackageTags>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="FluentMigrator" Version="6.2.0" />
	<PackageReference Include="FluentMigrator.Extensions.SqlServer" Version="6.2.0" />
	<PackageReference Include="FluentMigrator.Runner.SqlServer" Version="6.2.0" />	
	<PackageReference Include="FlyingFury.Libraries.ErrorHandling" Version="0.0.1" />	
	<PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="8.0.14" />	
	<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="8.0.14" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
	<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.2" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
  </ItemGroup>
</Project>
