<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PackageId>FlyingFury.Yeti.Persistence</PackageId>
	<Version>0.0.7</Version>
	<Authors>Steve Diersen</Authors>
	<Company>Flying Fury</Company>
	<Description>Database access layer for the Yeti project</Description>
	<PackageTags>Persistance; Database; FluentMigrator</PackageTags>
	<RepositoryType>git</RepositoryType>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<Copyright>Copyright © Flying Fury 2025</Copyright>
	<IncludeSource>True</IncludeSource>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="FluentMigrator" Version="7.0.0" />
	<PackageReference Include="FluentMigrator.Extensions.SqlServer" Version="7.0.0" />
	<PackageReference Include="FluentMigrator.Runner.SqlServer" Version="7.0.0" />	
	<PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.3" />	
	<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
	<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\$(Configuration)\$(TargetFramework)\Persistence.xml" Pack="true" PackagePath="lib\net9.0\" />
</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ErrorHandling\ErrorHandling.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\Identity\AccountRole\" />
    <Folder Include="Services\Identity\UserData\" />
    <Folder Include="Services\Transaction\CategoryItem\" />
    <Folder Include="Services\Transaction\Entry\" />
    <Folder Include="Services\Transaction\Item\" />
  </ItemGroup>	
</Project>
